//
// Autogenerated by Thrift Compiler (0.11.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var model_common_ttypes = require('./model_common_types');
var model_totalShare_ttypes = require('./model_totalShare_types');
var model_candidateList_ttypes = require('./model_candidateList_types');
var model_candidateDetail_ttypes = require('./model_candidateDetail_types');
var model_delegatorCandidateList_ttypes = require('./model_delegatorCandidateList_types');


var ttypes = module.exports = {};
