// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model_common.proto

package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Delegator struct {
	Address              string   `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	PubKey               string   `protobuf:"bytes,2,opt,name=pubKey" json:"pubKey,omitempty"`
	Shares               uint64   `protobuf:"varint,3,opt,name=shares" json:"shares,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Delegator) Reset()         { *m = Delegator{} }
func (m *Delegator) String() string { return proto.CompactTextString(m) }
func (*Delegator) ProtoMessage()    {}
func (*Delegator) Descriptor() ([]byte, []int) {
	return fileDescriptor_model_common_b8ae14361518fcb7, []int{0}
}
func (m *Delegator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Delegator.Unmarshal(m, b)
}
func (m *Delegator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Delegator.Marshal(b, m, deterministic)
}
func (dst *Delegator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Delegator.Merge(dst, src)
}
func (m *Delegator) XXX_Size() int {
	return xxx_messageInfo_Delegator.Size(m)
}
func (m *Delegator) XXX_DiscardUnknown() {
	xxx_messageInfo_Delegator.DiscardUnknown(m)
}

var xxx_messageInfo_Delegator proto.InternalMessageInfo

func (m *Delegator) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Delegator) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *Delegator) GetShares() uint64 {
	if m != nil {
		return m.Shares
	}
	return 0
}

type Candidate struct {
	Address              string                 `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	PubKey               string                 `protobuf:"bytes,2,opt,name=pubKey" json:"pubKey,omitempty"`
	Shares               uint64                 `protobuf:"varint,3,opt,name=shares" json:"shares,omitempty"`
	VotingPower          float64                `protobuf:"fixed64,4,opt,name=votingPower" json:"votingPower,omitempty"`
	Description          *Candidate_Description `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	Delegators           []*Delegator           `protobuf:"bytes,6,rep,name=delegators" json:"delegators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Candidate) Reset()         { *m = Candidate{} }
func (m *Candidate) String() string { return proto.CompactTextString(m) }
func (*Candidate) ProtoMessage()    {}
func (*Candidate) Descriptor() ([]byte, []int) {
	return fileDescriptor_model_common_b8ae14361518fcb7, []int{1}
}
func (m *Candidate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Candidate.Unmarshal(m, b)
}
func (m *Candidate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Candidate.Marshal(b, m, deterministic)
}
func (dst *Candidate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Candidate.Merge(dst, src)
}
func (m *Candidate) XXX_Size() int {
	return xxx_messageInfo_Candidate.Size(m)
}
func (m *Candidate) XXX_DiscardUnknown() {
	xxx_messageInfo_Candidate.DiscardUnknown(m)
}

var xxx_messageInfo_Candidate proto.InternalMessageInfo

func (m *Candidate) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Candidate) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *Candidate) GetShares() uint64 {
	if m != nil {
		return m.Shares
	}
	return 0
}

func (m *Candidate) GetVotingPower() float64 {
	if m != nil {
		return m.VotingPower
	}
	return 0
}

func (m *Candidate) GetDescription() *Candidate_Description {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *Candidate) GetDelegators() []*Delegator {
	if m != nil {
		return m.Delegators
	}
	return nil
}

type Candidate_Description struct {
	Details              string   `protobuf:"bytes,1,opt,name=details" json:"details,omitempty"`
	Identity             string   `protobuf:"bytes,2,opt,name=identity" json:"identity,omitempty"`
	Moniker              string   `protobuf:"bytes,3,opt,name=moniker" json:"moniker,omitempty"`
	Website              string   `protobuf:"bytes,4,opt,name=website" json:"website,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Candidate_Description) Reset()         { *m = Candidate_Description{} }
func (m *Candidate_Description) String() string { return proto.CompactTextString(m) }
func (*Candidate_Description) ProtoMessage()    {}
func (*Candidate_Description) Descriptor() ([]byte, []int) {
	return fileDescriptor_model_common_b8ae14361518fcb7, []int{1, 0}
}
func (m *Candidate_Description) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Candidate_Description.Unmarshal(m, b)
}
func (m *Candidate_Description) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Candidate_Description.Marshal(b, m, deterministic)
}
func (dst *Candidate_Description) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Candidate_Description.Merge(dst, src)
}
func (m *Candidate_Description) XXX_Size() int {
	return xxx_messageInfo_Candidate_Description.Size(m)
}
func (m *Candidate_Description) XXX_DiscardUnknown() {
	xxx_messageInfo_Candidate_Description.DiscardUnknown(m)
}

var xxx_messageInfo_Candidate_Description proto.InternalMessageInfo

func (m *Candidate_Description) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func (m *Candidate_Description) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *Candidate_Description) GetMoniker() string {
	if m != nil {
		return m.Moniker
	}
	return ""
}

func (m *Candidate_Description) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func init() {
	proto.RegisterType((*Delegator)(nil), "model.common.Delegator")
	proto.RegisterType((*Candidate)(nil), "model.common.Candidate")
	proto.RegisterType((*Candidate_Description)(nil), "model.common.Candidate.Description")
}

func init() { proto.RegisterFile("model_common.proto", fileDescriptor_model_common_b8ae14361518fcb7) }

var fileDescriptor_model_common_b8ae14361518fcb7 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0x87, 0xe5, 0xfe, 0x49, 0xc9, 0x85, 0xc9, 0x03, 0x58, 0x9d, 0xac, 0xb2, 0x64, 0xca, 0x50,
	0x06, 0x76, 0x28, 0x13, 0x0b, 0xb2, 0xc4, 0xc2, 0x82, 0x9c, 0xfa, 0x54, 0x2c, 0x12, 0x3b, 0xb2,
	0x0d, 0x11, 0x6f, 0xcd, 0x23, 0xa0, 0x98, 0x24, 0x98, 0x9d, 0xf1, 0xfb, 0xf9, 0xee, 0x74, 0xdf,
	0x19, 0x68, 0x6b, 0x15, 0x36, 0x2f, 0x47, 0xdb, 0xb6, 0xd6, 0x54, 0x9d, 0xb3, 0xc1, 0xd2, 0xf3,
	0x98, 0x55, 0x3f, 0xd9, 0xee, 0x09, 0xf2, 0x03, 0x36, 0x78, 0x92, 0xc1, 0x3a, 0xca, 0x60, 0x23,
	0x95, 0x72, 0xe8, 0x3d, 0x23, 0x9c, 0x94, 0xb9, 0x98, 0x90, 0x5e, 0x40, 0xd6, 0xbd, 0xd7, 0x0f,
	0xf8, 0xc9, 0x16, 0xf1, 0x61, 0xa4, 0x21, 0xf7, 0xaf, 0xd2, 0xa1, 0x67, 0x4b, 0x4e, 0xca, 0x95,
	0x18, 0x69, 0xf7, 0xb5, 0x80, 0xfc, 0x4e, 0x1a, 0xa5, 0x95, 0x0c, 0xf8, 0x7f, 0x73, 0x29, 0x87,
	0xe2, 0xc3, 0x06, 0x6d, 0x4e, 0x8f, 0xb6, 0x47, 0xc7, 0x56, 0x9c, 0x94, 0x44, 0xa4, 0x11, 0xbd,
	0x87, 0x42, 0xa1, 0x3f, 0x3a, 0xdd, 0x05, 0x6d, 0x0d, 0x5b, 0x73, 0x52, 0x16, 0xfb, 0xab, 0x2a,
	0x95, 0xae, 0xe6, 0xcd, 0xaa, 0xc3, 0x6f, 0xa9, 0x48, 0xfb, 0xe8, 0x0d, 0x80, 0x9a, 0xee, 0xe2,
	0x59, 0xc6, 0x97, 0x65, 0xb1, 0xbf, 0xfc, 0x3b, 0x65, 0xbe, 0x9b, 0x48, 0x4a, 0xb7, 0x3d, 0x14,
	0xc9, 0xd0, 0x41, 0x5d, 0x61, 0x90, 0xba, 0x99, 0xd5, 0x47, 0xa4, 0x5b, 0x38, 0xd3, 0x0a, 0x4d,
	0xd0, 0x61, 0x92, 0x9f, 0x79, 0xe8, 0x6a, 0xad, 0xd1, 0x6f, 0xe8, 0xa2, 0x7f, 0x2e, 0x26, 0x1c,
	0x5e, 0x7a, 0xac, 0xbd, 0x0e, 0x18, 0xe5, 0x73, 0x31, 0xe1, 0xed, 0xe6, 0x79, 0x1d, 0xd7, 0xab,
	0xb3, 0xf8, 0xcf, 0xd7, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2c, 0x90, 0xd3, 0x7c, 0xfd, 0x01,
	0x00, 0x00,
}
