// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model_delegatorCandidateList.proto

package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Ignoring public import of Delegator from model_common.proto

// Ignoring public import of Candidate from model_common.proto

// Ignoring public import of Description from model_common.proto

type DelegatorCandidateListRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Page                 uint64   `protobuf:"varint,2,opt,name=page" json:"page,omitempty"`
	PerPage              uint64   `protobuf:"varint,3,opt,name=perPage" json:"perPage,omitempty"`
	Sort                 string   `protobuf:"bytes,4,opt,name=sort" json:"sort,omitempty"`
	Q                    string   `protobuf:"bytes,5,opt,name=q" json:"q,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelegatorCandidateListRequest) Reset()         { *m = DelegatorCandidateListRequest{} }
func (m *DelegatorCandidateListRequest) String() string { return proto.CompactTextString(m) }
func (*DelegatorCandidateListRequest) ProtoMessage()    {}
func (*DelegatorCandidateListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_model_delegatorCandidateList_4a862483050f0037, []int{0}
}
func (m *DelegatorCandidateListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelegatorCandidateListRequest.Unmarshal(m, b)
}
func (m *DelegatorCandidateListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelegatorCandidateListRequest.Marshal(b, m, deterministic)
}
func (dst *DelegatorCandidateListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelegatorCandidateListRequest.Merge(dst, src)
}
func (m *DelegatorCandidateListRequest) XXX_Size() int {
	return xxx_messageInfo_DelegatorCandidateListRequest.Size(m)
}
func (m *DelegatorCandidateListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelegatorCandidateListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelegatorCandidateListRequest proto.InternalMessageInfo

func (m *DelegatorCandidateListRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *DelegatorCandidateListRequest) GetPage() uint64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *DelegatorCandidateListRequest) GetPerPage() uint64 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

func (m *DelegatorCandidateListRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *DelegatorCandidateListRequest) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

type DelegatorCandidateListResponse struct {
	Candidate            []*Candidate `protobuf:"bytes,1,rep,name=candidate" json:"candidate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DelegatorCandidateListResponse) Reset()         { *m = DelegatorCandidateListResponse{} }
func (m *DelegatorCandidateListResponse) String() string { return proto.CompactTextString(m) }
func (*DelegatorCandidateListResponse) ProtoMessage()    {}
func (*DelegatorCandidateListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_model_delegatorCandidateList_4a862483050f0037, []int{1}
}
func (m *DelegatorCandidateListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelegatorCandidateListResponse.Unmarshal(m, b)
}
func (m *DelegatorCandidateListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelegatorCandidateListResponse.Marshal(b, m, deterministic)
}
func (dst *DelegatorCandidateListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelegatorCandidateListResponse.Merge(dst, src)
}
func (m *DelegatorCandidateListResponse) XXX_Size() int {
	return xxx_messageInfo_DelegatorCandidateListResponse.Size(m)
}
func (m *DelegatorCandidateListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DelegatorCandidateListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DelegatorCandidateListResponse proto.InternalMessageInfo

func (m *DelegatorCandidateListResponse) GetCandidate() []*Candidate {
	if m != nil {
		return m.Candidate
	}
	return nil
}

func init() {
	proto.RegisterType((*DelegatorCandidateListRequest)(nil), "model_delegatorCandidateList.DelegatorCandidateListRequest")
	proto.RegisterType((*DelegatorCandidateListResponse)(nil), "model_delegatorCandidateList.DelegatorCandidateListResponse")
}

func init() {
	proto.RegisterFile("model_delegatorCandidateList.proto", fileDescriptor_model_delegatorCandidateList_4a862483050f0037)
}

var fileDescriptor_model_delegatorCandidateList_4a862483050f0037 = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xca, 0xcd, 0x4f, 0x49,
	0xcd, 0x89, 0x4f, 0x49, 0xcd, 0x49, 0x4d, 0x4f, 0x2c, 0xc9, 0x2f, 0x72, 0x4e, 0xcc, 0x4b, 0xc9,
	0x4c, 0x49, 0x2c, 0x49, 0xf5, 0xc9, 0x2c, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92,
	0xc1, 0xa7, 0x46, 0x4a, 0x08, 0x22, 0x9b, 0x9c, 0x9f, 0x9b, 0x9b, 0x9f, 0x07, 0xd1, 0xa1, 0xd4,
	0xc9, 0xc8, 0x25, 0xeb, 0x82, 0x55, 0x79, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x04,
	0x17, 0x7b, 0x62, 0x4a, 0x4a, 0x51, 0x6a, 0x71, 0xb1, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10,
	0x8c, 0x2b, 0x24, 0xc4, 0xc5, 0x52, 0x90, 0x98, 0x9e, 0x2a, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x12,
	0x04, 0x66, 0x83, 0x54, 0x17, 0xa4, 0x16, 0x05, 0x80, 0x84, 0x99, 0xc1, 0xc2, 0x30, 0x2e, 0x48,
	0x75, 0x71, 0x7e, 0x51, 0x89, 0x04, 0x0b, 0xd8, 0x10, 0x30, 0x5b, 0x88, 0x87, 0x8b, 0xb1, 0x50,
	0x82, 0x15, 0x2c, 0xc0, 0x58, 0xa8, 0x14, 0xce, 0x25, 0x87, 0xcb, 0x29, 0xc5, 0x05, 0xf9, 0x79,
	0xc5, 0xa9, 0x42, 0xa6, 0x5c, 0x9c, 0xc9, 0x30, 0x09, 0x09, 0x46, 0x05, 0x66, 0x0d, 0x6e, 0x23,
	0x71, 0x3d, 0x14, 0x5f, 0xc1, 0xf5, 0x05, 0x21, 0x54, 0x3a, 0xb1, 0x47, 0xb1, 0x82, 0x15, 0x05,
	0x30, 0x24, 0xb1, 0x81, 0xbd, 0x6d, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x40, 0x7a, 0x9f, 0xf2,
	0x4e, 0x01, 0x00, 0x00,
}
