// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model_candidateList.proto

package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Ignoring public import of Delegator from model_common.proto

// Ignoring public import of Candidate from model_common.proto

// Ignoring public import of Description from model_common.proto

type CandidateListRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Page                 uint64   `protobuf:"varint,2,opt,name=page" json:"page,omitempty"`
	PerPage              uint64   `protobuf:"varint,3,opt,name=perPage" json:"perPage,omitempty"`
	Sort                 string   `protobuf:"bytes,4,opt,name=sort" json:"sort,omitempty"`
	Q                    string   `protobuf:"bytes,5,opt,name=q" json:"q,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CandidateListRequest) Reset()         { *m = CandidateListRequest{} }
func (m *CandidateListRequest) String() string { return proto.CompactTextString(m) }
func (*CandidateListRequest) ProtoMessage()    {}
func (*CandidateListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_model_candidateList_0ddc4939afb7fd72, []int{0}
}
func (m *CandidateListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CandidateListRequest.Unmarshal(m, b)
}
func (m *CandidateListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CandidateListRequest.Marshal(b, m, deterministic)
}
func (dst *CandidateListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CandidateListRequest.Merge(dst, src)
}
func (m *CandidateListRequest) XXX_Size() int {
	return xxx_messageInfo_CandidateListRequest.Size(m)
}
func (m *CandidateListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CandidateListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CandidateListRequest proto.InternalMessageInfo

func (m *CandidateListRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CandidateListRequest) GetPage() uint64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *CandidateListRequest) GetPerPage() uint64 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

func (m *CandidateListRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *CandidateListRequest) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

type CandidateListResponse struct {
	Candidates           []*Candidate `protobuf:"bytes,1,rep,name=candidates" json:"candidates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CandidateListResponse) Reset()         { *m = CandidateListResponse{} }
func (m *CandidateListResponse) String() string { return proto.CompactTextString(m) }
func (*CandidateListResponse) ProtoMessage()    {}
func (*CandidateListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_model_candidateList_0ddc4939afb7fd72, []int{1}
}
func (m *CandidateListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CandidateListResponse.Unmarshal(m, b)
}
func (m *CandidateListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CandidateListResponse.Marshal(b, m, deterministic)
}
func (dst *CandidateListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CandidateListResponse.Merge(dst, src)
}
func (m *CandidateListResponse) XXX_Size() int {
	return xxx_messageInfo_CandidateListResponse.Size(m)
}
func (m *CandidateListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CandidateListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CandidateListResponse proto.InternalMessageInfo

func (m *CandidateListResponse) GetCandidates() []*Candidate {
	if m != nil {
		return m.Candidates
	}
	return nil
}

func init() {
	proto.RegisterType((*CandidateListRequest)(nil), "model.candidateList.CandidateListRequest")
	proto.RegisterType((*CandidateListResponse)(nil), "model.candidateList.CandidateListResponse")
}

func init() {
	proto.RegisterFile("model_candidateList.proto", fileDescriptor_model_candidateList_0ddc4939afb7fd72)
}

var fileDescriptor_model_candidateList_0ddc4939afb7fd72 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0xbf, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x31, 0x49, 0x88, 0x38, 0x98, 0x0c, 0x08, 0xc3, 0x14, 0x65, 0xca, 0x94, 0x01, 0x06,
	0x76, 0x58, 0x19, 0x22, 0x8f, 0x5d, 0x2a, 0xb7, 0x3e, 0x55, 0x91, 0x9a, 0xd8, 0xb1, 0xdd, 0xbd,
	0x7f, 0x7a, 0xe5, 0xcb, 0x0f, 0xa5, 0xdd, 0xee, 0xde, 0x7d, 0xb6, 0xde, 0x07, 0x1f, 0x9d, 0xd1,
	0x78, 0xdc, 0xee, 0x55, 0xaf, 0x5b, 0xad, 0x02, 0xfe, 0xb7, 0x3e, 0xd4, 0xd6, 0x99, 0x60, 0xf8,
	0x0b, 0x9d, 0xea, 0xab, 0xd3, 0x27, 0x9f, 0x78, 0xd3, 0x75, 0xa6, 0x1f, 0xc1, 0xf2, 0xcc, 0xe0,
	0xf5, 0x6f, 0x4d, 0x49, 0x1c, 0x4e, 0xe8, 0x03, 0x17, 0x90, 0x2b, 0xad, 0x1d, 0x7a, 0x2f, 0x58,
	0xc1, 0xaa, 0x47, 0x39, 0xaf, 0x9c, 0x43, 0x6a, 0xd5, 0x01, 0xc5, 0x7d, 0xc1, 0xaa, 0x54, 0xd2,
	0x1c, 0x69, 0x8b, 0xae, 0x89, 0x71, 0x42, 0xf1, 0xbc, 0x46, 0xda, 0x1b, 0x17, 0x44, 0x4a, 0x9f,
	0xd0, 0xcc, 0x9f, 0x81, 0x0d, 0x22, 0xa3, 0x80, 0x0d, 0x65, 0x03, 0x6f, 0x37, 0x0d, 0xbc, 0x35,
	0xbd, 0x47, 0xfe, 0x03, 0xb0, 0x08, 0xc4, 0x16, 0x49, 0xf5, 0xf4, 0xf5, 0x5e, 0x4f, 0x66, 0xa3,
	0xc4, 0xf2, 0x50, 0xae, 0xd0, 0xdf, 0x7c, 0x93, 0x11, 0xd5, 0xdc, 0xed, 0x1e, 0x48, 0xf3, 0xfb,
	0x12, 0x00, 0x00, 0xff, 0xff, 0x11, 0x90, 0x7b, 0xe8, 0x2c, 0x01, 0x00, 0x00,
}
