// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model_candidateDetail.proto

package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Ignoring public import of Delegator from model_common.proto

// Ignoring public import of Candidate from model_common.proto

// Ignoring public import of Description from model_common.proto

type CandidateDetailRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	PubKey               string   `protobuf:"bytes,2,opt,name=pubKey" json:"pubKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CandidateDetailRequest) Reset()         { *m = CandidateDetailRequest{} }
func (m *CandidateDetailRequest) String() string { return proto.CompactTextString(m) }
func (*CandidateDetailRequest) ProtoMessage()    {}
func (*CandidateDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_model_candidateDetail_8ef0317b5667fe45, []int{0}
}
func (m *CandidateDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CandidateDetailRequest.Unmarshal(m, b)
}
func (m *CandidateDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CandidateDetailRequest.Marshal(b, m, deterministic)
}
func (dst *CandidateDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CandidateDetailRequest.Merge(dst, src)
}
func (m *CandidateDetailRequest) XXX_Size() int {
	return xxx_messageInfo_CandidateDetailRequest.Size(m)
}
func (m *CandidateDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CandidateDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CandidateDetailRequest proto.InternalMessageInfo

func (m *CandidateDetailRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CandidateDetailRequest) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

type CandidateDetailResponse struct {
	Candidate            []*Candidate `protobuf:"bytes,1,rep,name=candidate" json:"candidate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CandidateDetailResponse) Reset()         { *m = CandidateDetailResponse{} }
func (m *CandidateDetailResponse) String() string { return proto.CompactTextString(m) }
func (*CandidateDetailResponse) ProtoMessage()    {}
func (*CandidateDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_model_candidateDetail_8ef0317b5667fe45, []int{1}
}
func (m *CandidateDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CandidateDetailResponse.Unmarshal(m, b)
}
func (m *CandidateDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CandidateDetailResponse.Marshal(b, m, deterministic)
}
func (dst *CandidateDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CandidateDetailResponse.Merge(dst, src)
}
func (m *CandidateDetailResponse) XXX_Size() int {
	return xxx_messageInfo_CandidateDetailResponse.Size(m)
}
func (m *CandidateDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CandidateDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CandidateDetailResponse proto.InternalMessageInfo

func (m *CandidateDetailResponse) GetCandidate() []*Candidate {
	if m != nil {
		return m.Candidate
	}
	return nil
}

func init() {
	proto.RegisterType((*CandidateDetailRequest)(nil), "model_candidateDetail.CandidateDetailRequest")
	proto.RegisterType((*CandidateDetailResponse)(nil), "model_candidateDetail.CandidateDetailResponse")
}

func init() {
	proto.RegisterFile("model_candidateDetail.proto", fileDescriptor_model_candidateDetail_8ef0317b5667fe45)
}

var fileDescriptor_model_candidateDetail_8ef0317b5667fe45 = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xce, 0xcd, 0x4f, 0x49,
	0xcd, 0x89, 0x4f, 0x4e, 0xcc, 0x4b, 0xc9, 0x4c, 0x49, 0x2c, 0x49, 0x75, 0x49, 0x2d, 0x49, 0xcc,
	0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0xc5, 0x2a, 0x29, 0x25, 0x04, 0x15, 0xce,
	0xcf, 0xcd, 0xcd, 0xcf, 0x83, 0x28, 0x55, 0xf2, 0xe2, 0x12, 0x73, 0x46, 0x55, 0x16, 0x94, 0x5a,
	0x58, 0x9a, 0x5a, 0x5c, 0x22, 0x24, 0xc1, 0xc5, 0x9e, 0x98, 0x92, 0x52, 0x94, 0x5a, 0x5c, 0x2c,
	0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe3, 0x0a, 0x89, 0x71, 0xb1, 0x15, 0x94, 0x26, 0x79,
	0xa7, 0x56, 0x4a, 0x30, 0x81, 0x25, 0xa0, 0x3c, 0xa5, 0x00, 0x2e, 0x71, 0x0c, 0xb3, 0x8a, 0x0b,
	0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x4c, 0xb9, 0x38, 0xe1, 0xae, 0x91, 0x60, 0x54, 0x60, 0xd6, 0xe0,
	0x36, 0x12, 0xd7, 0x43, 0x71, 0x0e, 0x5c, 0x67, 0x10, 0x42, 0xa5, 0x13, 0x7b, 0x14, 0x2b, 0x58,
	0x51, 0x00, 0x43, 0x12, 0x1b, 0xd8, 0xbd, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x21, 0xe1,
	0x17, 0x82, 0xf9, 0x00, 0x00, 0x00,
}
