// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model_totalShare.proto

package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TotalShareRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TotalShareRequest) Reset()         { *m = TotalShareRequest{} }
func (m *TotalShareRequest) String() string { return proto.CompactTextString(m) }
func (*TotalShareRequest) ProtoMessage()    {}
func (*TotalShareRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_model_totalShare_16987e8e99b580af, []int{0}
}
func (m *TotalShareRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TotalShareRequest.Unmarshal(m, b)
}
func (m *TotalShareRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TotalShareRequest.Marshal(b, m, deterministic)
}
func (dst *TotalShareRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TotalShareRequest.Merge(dst, src)
}
func (m *TotalShareRequest) XXX_Size() int {
	return xxx_messageInfo_TotalShareRequest.Size(m)
}
func (m *TotalShareRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TotalShareRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TotalShareRequest proto.InternalMessageInfo

func (m *TotalShareRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type TotalShareResponse struct {
	TotalShares          uint64   `protobuf:"varint,2,opt,name=totalShares" json:"totalShares,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TotalShareResponse) Reset()         { *m = TotalShareResponse{} }
func (m *TotalShareResponse) String() string { return proto.CompactTextString(m) }
func (*TotalShareResponse) ProtoMessage()    {}
func (*TotalShareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_model_totalShare_16987e8e99b580af, []int{1}
}
func (m *TotalShareResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TotalShareResponse.Unmarshal(m, b)
}
func (m *TotalShareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TotalShareResponse.Marshal(b, m, deterministic)
}
func (dst *TotalShareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TotalShareResponse.Merge(dst, src)
}
func (m *TotalShareResponse) XXX_Size() int {
	return xxx_messageInfo_TotalShareResponse.Size(m)
}
func (m *TotalShareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TotalShareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TotalShareResponse proto.InternalMessageInfo

func (m *TotalShareResponse) GetTotalShares() uint64 {
	if m != nil {
		return m.TotalShares
	}
	return 0
}

func init() {
	proto.RegisterType((*TotalShareRequest)(nil), "model.totalShare.TotalShareRequest")
	proto.RegisterType((*TotalShareResponse)(nil), "model.totalShare.TotalShareResponse")
}

func init() {
	proto.RegisterFile("model_totalShare.proto", fileDescriptor_model_totalShare_16987e8e99b580af)
}

var fileDescriptor_model_totalShare_16987e8e99b580af = []byte{
	// 128 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcb, 0xcd, 0x4f, 0x49,
	0xcd, 0x89, 0x2f, 0xc9, 0x2f, 0x49, 0xcc, 0x09, 0xce, 0x48, 0x2c, 0x4a, 0xd5, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x12, 0x00, 0x8b, 0xeb, 0x21, 0xc4, 0x95, 0x74, 0xb9, 0x04, 0x43, 0xe0, 0xbc,
	0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x09, 0x2e, 0xf6, 0xc4, 0x94, 0x94, 0xa2, 0xd4,
	0xe2, 0x62, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x18, 0x57, 0xc9, 0x8c, 0x4b, 0x08, 0x59,
	0x79, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x02, 0x17, 0x37, 0xc2, 0xc8, 0x62, 0x09, 0x26,
	0x05, 0x46, 0x0d, 0x96, 0x20, 0x64, 0x21, 0x27, 0xf6, 0x28, 0x56, 0xb0, 0xd5, 0x49, 0x6c, 0x60,
	0x87, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x6e, 0x4e, 0xb7, 0x05, 0xa2, 0x00, 0x00, 0x00,
}
